import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

/*
Good to know:

- The app directory must include a root layout.

- The root layout must define <html> and <body> tags since 
  Next.js does not automatically create them.

- You can use the built-in SEO support to manage <head> HTML 
  elements, for example, the <title> element.

- You can use route groups to create multiple root layouts. 
  See an example here.
  
- The root layout is a Server Component by default and can not 
  be set to a Client Component.
*/
